sudo: false

language: go

go:
 - 1.12.x
 - master

env:
 global:
  - GO111MODULE=on

cache:
 directories:
   - $HOME/.cache/go-build
   - $HOME/gopath/pkg/mod

git:
 depth: 1

go_import_path: github.com/dreading/gospecfunc

# Get deps, build, test, and ensure the code is gofmt'ed.
# If we are building as gonum, then we have access to the coveralls api key, so we can run coverage as well.
script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test $TAGS -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
